export interface AntecedentesPersonalesPatologicos {
  id: number,
  cirujias: string;
  espCirujias: string;
  contusiones: string;
  espContusiones: string;
  lumbalgias: string;
  espLumbalgias: string;
  hernias: string;
  espHernias: string;
  fracturas: string;
  espFracturas: string;
  dorsalgias: string;
  espDorsalgias: string;
  hospitalizaciones: string;
  espHospitalizaciones: string;
  esguinces: string;
  espEsguinces: string;
  lesionesArteriales: string;
  espLesionesArteriales: string;
  transfusiones: string;
  espTransfusiones: string;
  luxaciones: string;
  espLuxaciones: string;
  tetanias: string;
  espTetanias: string;
  alergias: string;
  espAlergias: string;
  asma: string;
  epilepsia: string;
  enfDentales: string;
  espEnfDentales: string;
  enfOpticas: string;
  espEnfOpticas: string;
  altPsicologicas: string;
  espAltPsicologicas: string;
}